pub const TOKEN_PATH_ENV_VAR: &str = "NAKADION_ACCESS_TOKEN_PATH";
pub const TOKEN_FIXED_ENV_VAR: &str = "NAKADION_ACCESS_TOKEN_FIXED";
pub const ALLOW_NO_TOKEN_ENV_VAR: &str = "NAKADION_ACCESS_TOKEN_ALLOW_NONE";
pub const NAKADION_NAKADI_HOST_ENV_VAR: &str = "NAKADION_NAKADI_HOST";

pub const NAKADION_SUBSCRIPTION_ID_ENV_VAR: &str = "NAKADION_SUBSCRIPTION_ID";
pub const NAKADION_EVENT_TYPE_ENV_VAR: &str = "NAKADION_EVENT_TYPE";
