pub const NAKADION_NAKADI_HOST_ENV_VAR: &str = "NAKADION_NAKADI_HOST";

pub const TOKEN_PATH_ENV_VAR: &str = "NAKADION_ACCESS_TOKEN_PATH";
pub const TOKEN_FIXED_ENV_VAR: &str = "NAKADION_ACCESS_TOKEN_FIXED";
pub const ALLOW_NO_TOKEN_ENV_VAR: &str = "NAKADION_ACCESS_TOKEN_ALLOW_NONE";

pub const NAKADION_SUBSCRIPTION_ID_ENV_VAR: &str = "NAKADION_SUBSCRIPTION_ID";
pub const NAKADION_EVENT_TYPE_ENV_VAR: &str = "NAKADION_EVENT_TYPE";

pub const NAKADION_MAX_UNCOMMITTED_EVENTS_ENV_VAR: &str = "NAKADION_MAX_UNCOMMITTED_EVENTS";
pub const NAKADION_BATCH_LIMIT_ENV_VAR: &str = "NAKADION_BATCH_LIMIT";
pub const NAKADION_BATCH_FLUSH_TIMEOUT_SECS_ENV_VAR: &str = "NAKADION_BATCH_FLUSH_TIMEOUT_SECS";
pub const NAKADION_STREAM_TIMEOUT_SECS_ENV_VAR: &str = "NAKADION_STREAM_TIMEOUT_SECS";
pub const NAKADION_STREAM_LIMIT_ENV_VAR: &str = "NAKADION_STREAM_LIMIT";
pub const NAKADION_STREAM_KEEP_ALIVE_LIMIT_ENV_VAR: &str = "NAKADION_STREAM_KEEP_ALIVE_LIMIT";
