name: CI

on: [push, pull_request]

jobs:
  build_nakadion:
    name: Build Nakadion
    strategy:
      matrix:
        features: ["--no-default-features", "--all-features", "--features metrix", ""]
        rust: [
          1.41.0, # MSRV
          nightly # it is good practise to test libraries against nightly to catch regressions in the compiler early
        ]
      fail-fast: false # don't want to kill the whole CI if nightly fails
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Cache target directory
        uses: actions/cache@v1
        with:
          path: target
          key: target-directory-${{ matrix.rust }}-${{ matrix.features }}-${{ hashFiles('Cargo.toml') }}
      - run: cargo build --manifest-path=./nakadi-types/Cargo.toml
      - run: cargo test --manifest-path=./nakadi-types/Cargo.toml
      - run: cargo build  ${{ matrix.features }} --manifest-path=./nakadion/Cargo.toml
      - run: cargo test  ${{ matrix.features }} --manifest-path=./nakadion/Cargo.toml
      - name: Run integration test against Nakadi
        if: matrix.rust != 'nightly' && matrix.features == ''
        run: |
          git clone https://github.com/adyach/nakadi-docker
          (cd nakadi-docker && docker-compose up -d)
          while ! METRICS=$(curl -s "localhost:8080/metrics"); do sleep 5; done; echo $METRICS
          export DEBUG_LOGGING_ENABLED=true
          cargo run -p nakadion --example integration
